### ISSUE TITLE
reduce distribution size

### ISSUE THREAD

**Issue by casperdcl** [SyneRBI/SIRF-SuperBuild#101]
It would be nice if we could reduce the size of the distributed VM/docker images by removing unneeded files.

Ideas:

- `apt-get autoremove && apt-get clean`
- removing intermediate files (e.g. *.cpp -> *.o -> *.so means we can remove *.o)
- removing all sources (binary-only)
  + TODO: how? Preferably more sophisticated than `find -name "*.cpp" -exec rm \{} \;`
- only have the sources downloaded but not yet built
  + we run `cmake -DDOWNLOAD_ONLY=ON && make -j && cmake -DDOWNLOAD_ONLY=OFF`, the end user runs `make` just once

I'm pretty sure we can reduce sizes by hundreds of megabytes

**Comment by KrisThielemans** [comment]
`apt-get` cleaning is definitely a good idea. no idea if it makes any difference.

I think this is a bit different for the VM or docker image. The docker one is an "install" thing only. If you want to update SIRF, you grab a new docker image. So for that, keeping only installed stuff makes 100% sense. In contrast, for the VM, our motivation to keep *.o etc is that an update will then be a lot faster (assuming we don't update tags for everything). Removing *.cpp is hardly going to do anything.

For the VM, there would be 3 sensible options:
- keep as-is (fast update, larger disk space, longer download)
- keep only binaries and demos+data
- distribute almost bare VM. Tell people to type "update_VM.sh" and it will all happen. (This essentially means skipping one step in the `vagrantfile`).

Removing source distribution is currently a bit more complicated than just removing the build directory due to #102.

Is it important to invest time in this?

**Comment by KrisThielemans** [comment]
Given complications in #102 (probably resolved, but anyway), I suggest to save our docker images with removing the following in `builds`:
- ITK
- HDF5
- STIR

I guess `builds/SIRF` could also be removed, but I'm a bit less sure about that. @evgueni-ovtchinnikov, what do you think?

**Comment by KrisThielemans** [comment]
@paskino feel like trying that (in a new PR)?
