### ISSUE TITLE
GTEST_ROOT is not present if not building GTest

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#126]
https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_GTest.cmake#L75 will not set `GTEST_ROOT` rather [`GTEST_LIBRARIES`](https://cmake.org/cmake/help/v3.11/module/FindGTest.html).

**Comment by KrisThielemans** [comment]
I think `GTEST_ROOT` "may be set" by the user, not by the `FindGTest.cmake`. Could check on the [source](https://github.com/Kitware/CMake/blob/master/Modules/FindGTest.cmake).

Using `GTEST_LIBRARIES` is fraught with difficulties as you don't know what's in there, an din any case can't be passed on.

This is a common problem in the SuperBuild: we need to ensure that "ours" is found if we build it, but otherwise we have to rely on usual CMake stuff.

We've tried `mark_as_superbuild` to work-around this, but it wouldn't cope with the `USE_SYSTEM_*=OFF` case where the user sets `GTEST_ROOT`.

I suppose the thing to do is to only pass `GTEST_ROOT` if it is actually set (either by us, or by the user). That'd need a change [here for Gadgetron](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/0c327c0b495ef2c798edd3c76108a0a5f53cc2de/SuperBuild/External_Gadgetron.cmake#L98).

I think the best strategy is probably to create a variable `GTEST_CMAKE_FLAGS` in `External_GTest.cmake` which would be setting `GTEST_ROOT` if it needs to, and otherwise be empty, and use that in dependent packages. That should work for all packages I believe.

**Comment by KrisThielemans** [comment]
maybe you're right. cases:
- `USE_SYSTEM_GTEST=ON`: we set `GTEST_ROOT`
- `USE_SYSTEM_GTEST=OFF`: 
  - the user sets `GTEST_ROOT`, so we'll pass it on
  - the user doesn't set `GTEST_ROOT`, so we set it to empty when calling CMake for Gadgetron.

Actually seems fine. If you agree, please close this issue.

I still think that a strategy if introducing `GTEST_CMAKE_FLAGS`, `STIR_CMAKE_FLAGS` etc would be nice and clean, but that's for another issue then (if you agree with it, please create a new one)
