### ISSUE TITLE
Docker tags

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-SuperBuild#507]
I'm not clear on the Docker tags and versions. We have some instructions in the Wiki:
https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/README.md 

but on Docker Hub, the only recent versions have tags 'core' and 'core-gpu'.

**Comment by KrisThielemans** [comment]
This is due to failures building/test. Current read-block is #506 which is due to CIL. I hope that @paskino, @gfardell or @epapoutsellis can have a look at what extra bits we need to install. Once that's fixed, the files on dockerhub should get automatically updated. I'm therefore closing this issue.
