### ISSUE TITLE
gpu docker does not start. 

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF-SuperBuild#587]
```
$ ./sirf-compose-server-gpu up -d sirf
ERROR: The Compose file './docker-compose.srv-gpu.yml' is invalid because:
Unsupported config option for services.gadgetron: 'runtime'
Unsupported config option for services.sirf: 'runtime'
```

I can run the non-GPU one normally.

**Comment by AnderBiguri** [comment]
This is on me I think, something to do with the version of docker-compose.... fixing on my side....

**Comment by KrisThielemans** [comment]
I think there was an issue on this already? I believe you need to upgrade your docker or at least docker-compose

Kris
________________________________
From: Biguri ***@***.***>
Sent: Wednesday, June 16, 2021 10:02:11 PM
To: SyneRBI/SIRF-SuperBuild ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SyneRBI/SIRF-SuperBuild] gpu docker does not start. (#587)


$ ./sirf-compose-server-gpu up -d sirf
ERROR: The Compose file './docker-compose.srv-gpu.yml' is invalid because:
Unsupported config option for services.gadgetron: 'runtime'
Unsupported config option for services.sirf: 'runtime'


I can run the non-GPU one normally.

**Comment by AnderBiguri** [comment]
Indeed. 

```
sudo pip uninstall docker-compose
pip3 install docker-compose 
```

**Comment by AnderBiguri** [comment]
Can verify this works well. (GPU docker)

**Comment by KrisThielemans** [comment]
can you add this (at the end?) of the `docker/README`? ("if you see this error, do that...")
