### ISSUE TITLE
Error in import sirf.STIR

### ISSUE THREAD

**Issue by Enza-994** [SyneRBI/SIRF-SuperBuild#774]
ImportError: libismrmrd.so.1.7: cannot open shared object file: No such file or directory, when importing sirf.STIR.
I've installed CMake version 3.21.3 and followed the instructions for installation on https://github.com/SyneRBI/SIRF-SuperBuild, by running:  cmake -DBUILD_Gadgetron:BOOL=OFF -DSIRF_EXTRA_CMAKE_ARGS="-DDISABLE_Gadgetron:BOOL=OFF" ../SIRF-SuperBuild (since Gadgetron was giving problems).

**Comment by KrisThielemans** [comment]
Did you `source ..../env_sirf.sh` which should set `PYTHONPATH`.

what's your OS by the way?

**Comment by Enza-994** [comment]
Hello,
I've tried to source ..../env_sirf.sh, but the problem still persists.
My OS is Ubuntu

**Comment by KrisThielemans** [comment]
what is the content after sourcing of `LD_LIBRARY_PATH`? Did you run the same python as what it used for building (could use `$SIRF_PYTHON_EXECUTABLE`). Is the `libismrmrd.so.1.7` in the expected location? (i.e. `/wherever/you/installed/lib`).

**Comment by Enza-994** [comment]
After sourcing ..../env_sirf.sh, the content of the different paths is the following:
echo $PYTHONPATH gives ../devel/build/INSTALL/python
echo $LD_LIBRARY_PATH gives ../devel/build/INSTALL/lib
echo $SIRF_PYTHON_EXECUTABLE gives ../devel/build/INSTALL/python (or what do you mean by using $SIRF_PYTHON_EXECUTABLE?)
Then, locate libismrmrd.so.1.7.0 gives ../devel/build/INSTALL/lib/libismrmrd.so.1.7.0, so the library is in the expected location

Thank you

**Comment by KrisThielemans** [comment]
`$SIRF_PYTHON_EXECUTABLE ` should be set to something like `/usr/bin/python3`, so that confuses me a bit. If you have 2 different Python versions installed (often `python` and `python3`, or a conda python or ...), it's important to run the same Python version as the one that CMake found. 

All other variables should contain absolute paths. If they don't, that could explain your problem (but maybe you just wrote `..` as shorthand).

If all that isn't it, you should send us the output of
```
ldd $PYTHONPATH/sirf/_pysirf.so
ldd $LD_LIBRARY_PATH/libismrmrd.so.1.7.0
```

Note that if `$SIRF_PYTHON_EXECUTABLE ` is a  python 2.* version, it'll probably be best to start over (in a new directory) by using
```
cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 <other-arguments>
```

Finally, on Ubuntu, you can save some compilation time (and potentially conflicts) but using more system libraries. If you want to go that path, I would recommend making sure they are installed via
```
cd SIRF-SuperBuild/docker;
sudo bash raw-ubuntu.sh;
sudo bash build_essential-ubuntu.sh;
sudo bash build_python-ubuntu.sh;
sudo bash build_gadgetron-ubuntu.sh;
sudo bash build_system-ubuntu.sh;
```
(note that a different set of instructions currently applies when using conda) and then
```
cd ~/devel/build
cmake -USIRF_TAG -USTIR_TAG -UBOOST\* -UBoost* -UHDF5*  -DUSE_SYSTEM_Boost:BOOL=ON -DUSE_SYSTEM_HDF5:BOOL=ON  -DDISABLE_Matlab:BOOL=ON  -DBUILD_Gadgetron:BOOL=OFF   -DPYTHON_EXECUTABLE=/usr/bin/python3  ../SIRF-SuperBuild
```
that's of course ridiculously complicated. Sorry about that! It's on our list...

**Comment by KrisThielemans** [comment]
can't see anything wrong... I do see it links to python 3.10. Are you sure you're using that to run as well? If you are, then I guess I'd repeat the above but from in python (i.e. start python, and do a system call to do the `ldd` calls). If that doesn't show anything missing, I'm out of ideas...

**Comment by KrisThielemans** [comment]
If the above fails, I'm wondering if there's something weird going on when using `-DSIRF_EXTRA_CMAKE_ARGS="-DDISABLE_Gadgetron:BOOL=OFF"`. Could try to set that to `ON`

**Comment by paskino** [comment]
it does say
```
libpython3.10.so.1.0 => not found
```
which isn't a great message.

**Comment by KrisThielemans** [comment]
true, but presumably calling `python3` (or whatever) would fix that.

Maybe safest is to do the `ldd` call from whithin python:
1. start python
2. `os.system('ldd $PYTHONPATH/sirf/_pysirf.so')`

**Comment by KrisThielemans** [comment]
Closing as no response. Feel free to re-open.
