### ISSUE TITLE
Docker README question

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#888]
README on "Extending" says
```
FROM synerbi/sirf:jupyter-gpu
```
is ghcr.io missing? I have no idea...

**Comment by casperdcl** [comment]
we tag for both registries https://github.com/SyneRBI/SIRF-SuperBuild/blob/fd4e9720965f846889e468eb938c88e5805ff5d3/.github/workflows/docker.yml#L39-L40
including login creds https://github.com/SyneRBI/SIRF-SuperBuild/blob/fd4e9720965f846889e468eb938c88e5805ff5d3/.github/workflows/docker.yml#L51-L61
and push https://github.com/SyneRBI/SIRF-SuperBuild/blob/fd4e9720965f846889e468eb938c88e5805ff5d3/.github/workflows/docker.yml#L108

so the `ghcr.io` is optional. I use it explicitly in GHA as it should be quicker due to physical server locations.
